build:
    nodes:
        analysis:
            project_setup:
                override:
                - 'true'
            codestyle:
                override:
                - php-scrutinizer-run
                - command: phpcs-run
        tests: true
        coverage:
            tests:
                override:
                - command: vendor/bin/phpunit --coverage-clover=coverage.xml
                  coverage:
                      file: coverage.xml
                      format: clover
filter:
    paths:
    - 'app/*'
    excluded_paths:
    - 'app/views/*'
    - 'app/config/*'
    - 'app/database/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true